import {
  ChatInputCommandInteraction,
  Client,
  SlashCommandBuilder,
  PermissionFlagsBits,
  TextChannel,
  EmbedBuilder,
  ColorResolvable,
} from "discord.js";
import { Command } from "../../types/index";
import { getTicketByChannel } from "../../tickets";
import { buildTranscript } from "../../utils/transcript";
import { getOrCreateGuildSettings } from "../../utility";
import { errorEmbed } from "../../utils/embed";
import config from "../../../config.json";

export default {
  data: new SlashCommandBuilder()
    .setName("transcript")
    .setDescription("Generate a transcript of this ticket without closing it."),

  async execute(interaction: ChatInputCommandInteraction, _client: Client): Promise<void> {
    const ticket = await getTicketByChannel(interaction.channelId);

    if (!ticket) {
      await interaction.reply({
        embeds: [errorEmbed("Not a Ticket", "This command can only be used inside a ticket channel.")],
      });
      return;
    }

    const member = await interaction.guild!.members.fetch(interaction.user.id);
    const isStaff =
      member.permissions.has(PermissionFlagsBits.ManageChannels) ||
      member.permissions.has(PermissionFlagsBits.Administrator);

    if (!isStaff) {
      await interaction.reply({
        embeds: [errorEmbed("No Permission", "Only staff can generate transcripts.")],
      });
      return;
    }

    await interaction.deferReply();

    const channel = interaction.channel as TextChannel;
    const buf = await buildTranscript(channel, ticket);

    const settings = await getOrCreateGuildSettings(interaction.guildId!);

    const embed = new EmbedBuilder()
      .setColor(config.color.info as ColorResolvable)
      .setTitle(`📋 Transcript — Ticket #${ticket.id}`)
      .addFields(
        { name: "Ticket ID", value: `#${ticket.id}`, inline: true },
        { name: "Opened By", value: `<@${ticket.user_id}>`, inline: true },
        { name: "Status", value: ticket.status, inline: true },
        { name: "Generated By", value: `${interaction.user}`, inline: true }
      )
      .setTimestamp();

    await interaction.editReply({
      embeds: [embed],
      files: [{ name: `ticket-${ticket.id}-transcript.txt`, attachment: buf }],
    });

    if (settings.ticket_log && settings.ticket_log !== interaction.channelId) {
      const logChannel = interaction.guild!.channels.cache.get(settings.ticket_log) as
        | TextChannel
        | undefined;
      if (logChannel) {
        await logChannel.send({
          embeds: [embed],
          files: [{ name: `ticket-${ticket.id}-transcript.txt`, attachment: buf }],
        });
      }
    }
  },
} satisfies Command;
